version: "3.9"

services:

  anchor1:
    build: .
    command: cle-anchor
    volumes:
      - .:/code
    environment:
      - CLE_ANCHOR_ID=1
      - CLE_ANCHOR_SOURCE_FILE=source.log

  anchor2:
    build: .
    command: python anchor/em.py
    volumes:
      - .:/code
    environment:
      - CLE_ANCHOR_ID=2
      - CLE_ANCHOR_SOURCE_FILE=source.log

  anchor3:
    build: .
    command: python anchor/em.py
    volumes:
      - .:/code
    environment:
      - CLE_ANCHOR_ID=3
      - CLE_ANCHOR_SOURCE_FILE=source.log

  anchor4:
    build: .
    command: python anchor/em.py
    volumes:
      - .:/code
    environment:
      - CLE_ANCHOR_ID=4
      - CLE_ANCHOR_SOURCE_FILE=source.log

  db:
    image: postgres
    volumes:
      - postgress:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"

  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_DB=testDB
    volumes:
      - influx:/var/lib/influxdb

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data/:/var/lib/rabbitmq/
      - rabbitmq-log/:/var/log/rabbitmq

  zero:
    build: .
    command: python3 zero.py
    volumes:
      - .:/code

  poller:
    build: .
    command: python poller.py
    volumes:
      - .:/code

  tst:
    build: .
    command: python influxdb.py
    volumes:
      - .:/code

  tst2:
    build: .
    command: python rabbit_recieve.py
    volumes:
      - .:/code


volumes:
  postgress:
  influx:
  rabbitmq-data:
  rabbitmq-log:
